version: '3'
services:
  # when using compose, the services names can be use as domain urls (e.g.: postgres:5432, redis:6379, server:5000, client:3000)
  postgres:
    image: 'postgres:latest'
  redis:
    image: 'redis:latest'
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules #bookmark
      - ./server:/app #everything except the prev bookmark is going to ve shared
    environment:
      - REDIS_HOST=redis # no need a url, in this case docker is going to look for a service called redis (the one declared previously)
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres # this is again the service declared above
      - PGDATABASE=postgres #default value in postgres image
      - PGPASSWORD=postgres_password # default value in postgres image
      - PGPORT=5432
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis # no need a url, in this case docker is going to look for a service called redis (the one declared previously)
      - REDIS_PORT=6379